# Generated by Django 4.1.3 on 2022-12-17 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
