# Generated by Django 4.1.3 on 2022-12-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdapp', '0002_alter_datasetfile_date_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetfile',
            options={'ordering': ['-date_creation'], 'verbose_name_plural': 'DatasetFiles'},
        ),
    ]
