version: '3'

services:
  postgresql_db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: pdapp
      POSTGRES_USER: nikitap
      POSTGRES_PASSWORD: postH6304!hA-01
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/db:/var/lib/postgresql/data

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DEBUG: "true"
      DATABASE_URL: "postgresql://nikitap:postH6304!hA-01@postgresql_db:5432/pdapp"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql_db